# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EmTCUIC5i9CCWa7W7Og9457uBgXL-u5u
"""



"""# Task
Generate Python code using matplotlib and numpy to create a triangle, and then apply translate, rotate, and scale transformations to it, and visualize the result.

## Create a triangle

### Subtask:
Generate code to create a triangle using matplotlib.

**Reasoning**:
Generate code to create a triangle using matplotlib and numpy.
"""

import matplotlib.pyplot as plt
import numpy as np

# Define the vertices of the triangle
triangle = np.array([[0, 0], [1, 0], [0.5, 1], [0, 0]])

# Create a figure and axes
fig, ax = plt.subplots()

# Plot the original triangle
ax.plot(triangle[:, 0], triangle[:, 1])

# Set aspect ratio and limits
ax.set_aspect('equal')
ax.set_xlim([-0.5, 1.5])
ax.set_ylim([-0.5, 1.5])

# Add a title
ax.set_title("Original Triangle")

# Show the plot
plt.show()

"""## Apply transformations

### Subtask:
Generate code to apply translate, rotate, and scale transformations to the triangle.

**Reasoning**:
Define translation, rotation, and scaling transformation matrices and apply them sequentially to the triangle vertices.
"""

# Define translation, rotation, and scaling matrices
translation_matrix = np.array([[1, 0, 1], [0, 1, 0.5], [0, 0, 1]])
angle = np.radians(45)
rotation_matrix = np.array([[np.cos(angle), -np.sin(angle), 0],
                            [np.sin(angle), np.cos(angle), 0],
                            [0, 0, 1]])
scaling_matrix = np.array([[2, 0, 0], [0, 0.5, 0], [0, 0, 1]])

# Convert triangle vertices to homogeneous coordinates
triangle_homogeneous = np.hstack((triangle[:-1], np.ones((triangle[:-1].shape[0], 1))))

# Apply transformations
translated_triangle = (translation_matrix @ triangle_homogeneous.T).T
rotated_triangle = (rotation_matrix @ translated_triangle.T).T
scaled_triangle = (scaling_matrix @ rotated_triangle.T).T

# Convert back to Cartesian coordinates
transformed_triangle = np.vstack((scaled_triangle[:, :2], scaled_triangle[0, :2]))

display(transformed_triangle)

"""## Visualize the result

### Subtask:
Generate code to visualize the transformed triangle.

**Reasoning**:
Generate code to visualize both the original and transformed triangles on the same plot, following the instructions to create a figure and axes, plot both triangles, set the aspect ratio, add labels, a legend, and a title.
"""

fig, ax = plt.subplots()

# Plot the original triangle
ax.plot(triangle[:, 0], triangle[:, 1], label='Original Triangle')

# Plot the translated triangle
# Ensure the translated_triangle is closed for plotting by appending the first vertex
ax.plot(np.append(translated_triangle[:, 0], translated_triangle[0, 0]),
        np.append(translated_triangle[:, 1], translated_triangle[0, 1]), label='Translated Triangle')

# Plot the transformed triangle
ax.plot(transformed_triangle[:, 0], transformed_triangle[:, 1], label='Transformed Triangle')

# Set the aspect ratio to 'equal'
ax.set_aspect('equal')

# Add labels to the x and y axes
ax.set_xlabel('X-axis')
ax.set_ylabel('Y-axis')

# Add a legend
ax.legend()

# Add a title
ax.set_title('Original and Transformed Triangle')

# Show the plot
plt.show()

"""## Summary:

### Data Analysis Key Findings

*   The original triangle was defined by the vertices (0, 0), (1, 0), and (0.5, 1).
*   The transformations applied were: a translation by (1, 0.5), a rotation by 45 degrees, and a scaling by factors of 2 in the x-direction and 0.5 in the y-direction.
*   The transformations were applied sequentially: translate, then rotate, then scale.
*   The final transformed triangle vertices were calculated and visualized alongside the original triangle.

### Insights or Next Steps

*   The visualization clearly shows the combined effect of the translation, rotation, and scaling on the original triangle.
*   This process can be extended to apply other types of 2D transformations or to transform more complex shapes.

"""